=== Create a contact list
____
This scenario describes how to use the functionality of Address Book API.

*Expected results*:

* Contact data of three external people are imported: +++Antoine_LaVey@mailme.com, Kesha_Williams@investor.biz, Juanita_Ma@hongkongexchange.hk+++.
* A custom _contact list_ is created.

*Related topics*: <<general/overview.adoc#address-book-api,Address Book API>>.
____

[float]
==== 1. Import contacts into the address book

_Address book_ lists all the contact information of all InfoNgen _users_.
This information can be used to subscribe other _users_ to your _searches_ or _newsletters_.
However, you may need to subscribe external _contacts_—people or organizations without direct access to InfoNgen—to provide them with the necessary information.

To add these three people to your _address book_, run the following POST method:

* Populate the `"email"` values in the array with the emails of your _contacts_.
* Optional: populate the `"first_name"` and `"last_name"` fields with the necessary data.

----
curl --location --request POST 'https://{{API_link}}/addressbook/contacts' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw
----
[source.json]
----
'[
    {
        "email": "Antoine_LaVey@mailme.com",
        "first_name": "Antoine",
        "last_name": "LaVey"
    },
    {
        "email": "Kesha_Williams@investor.biz",
        "first_name": "Kesha",
        "last_name": "Williams"
    },
    {
        "email": "Juanita_Ma@hongkongexchange.hk",
        "first_name": "Juanita",
        "last_name": "Ma"
    }
]'
----
.Click here for Address Book API response with created _contacts_.
[%collapsible]
====
Note that InfoNgen automatically assigned the necessary values of the `"id"` and `"type"` parameters to your _contacts_.

----
HTTP/1.1 202 Accepted
Content-Type: application/json
----

[source,json]
----
[
    {
        "id": "6655dbbcc24cb56fb205e53bb015595c",
        "email": "Antoine_LaVey@mailme.com",
        "first_name": "Antoine",
        "last_name": "LaVey",
        "type": "personal"
    },
    {
        "id": "6664d12f6823297a859f25cf87534fa1",
        "email": "Kesha_Williams@investor.biz",
        "first_name": "Kesha",
        "last_name": "Williams",
        "type": "personal"
    },
    {
        "id": "66707bb0bd445fdc47fb84cf557dfd15",
        "email": "Juanita_Ma@hongkongexchange.hk",
        "first_name": "Juanita",
        "last_name": "Ma",
        "type": "personal"
    }
]
----
====

InfoNgen created three _contacts_, assigned a unique ID (the value of the `"id"` parameter), and set a `"type": "personal"` key-value pair for each of them.

[float]
==== 2. Create a contact list with the new contacts

The _contacts_ can be subscribed to a _search_ or a _newsletter_ either separately or as a bundle.
Subscription to a _search_ is covered by the <<#subscribe-to-a-search,Subscribe to a _search_>> scenario. +
In case of subscribing them all together, create a _contact list_ first by running the following  POST request:

* Populate the `"contacts"` array with the IDs of your contacts. +
All other fields (`"first_name"`, `"last_name"`, `"email"`, and `"type"`) are optional for this request.
* Set a name for the _contact list_ in the `"name"` parameter.

----
curl --location --request POST 'https://{{API_link}}/addressbook/contact_lists' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw
----
[source,json]
----
'{
    "contacts": [
        {
            "id": "6655dbbcc24cb56fb205e53bb015595c"
        },
        {
            "id": "6664d12f6823297a859f25cf87534fa1"
        },
        {
            "id": "66707bb0bd445fdc47fb84cf557dfd15"
        }
    ],
    "name": "Externals"
}'
----

The response returns the `201 Created` status code, which means that the request was successful.
----
HTTP/1.1 201 Created
Content-Type: application/json
----

Check the result by running the following GET request:
----
curl --location --request GET 'https://{{API_link}}/addressbook' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for Address Book API response with the updated data.
[%collapsible]
====
InfoNgen returns two arrays—`"contacts"` and `"contact_lists"`—containing the data about all _users_, _contacts_, and _contact lists_. +
The data in the `"contact_lists"` array are automatically parsed from the `"contacts"` array.

----
HTTP/1.1 200 OK
Content-Type: application/json
----

[source,json]
----
{
    "contacts": [
        {
            "id": "b34567890123456f8f1e12d891474d2e",
            "email": "John_Wick@Fortune500company.com",
            "first_name": "John",
            "last_name": "Wick",
            "type": "corporate"
        },
        {
            "id": "6655dbbcc24cb56fb205e53bb015595c",
            "email": "Antoine_LaVey@mailme.com",
            "first_name": "Antoine",
            "last_name": "LaVey",
            "type": "personal"
        },
        {
            "id": "6664d12f6823297a859f25cf87534fa1",
            "email": "Kesha_Williams@investor.biz",
            "first_name": "Kesha",
            "last_name": "Williams",
            "type": "personal"
        },
        {
            "id": "66707bb0bd445fdc47fb84cf557dfd15",
            "email": "Juanita_Ma@hongkongexchange.hk",
            "first_name": "Juanita",
            "last_name": "Ma",
            "type": "personal"
        }
    ],
    "contact_lists": [
        {
            "id": 3362,
            "name": "Externals",
            "contacts": [
                {
                    "id": "6664d12f6823297a859f25cf87534fa1",
                    "email": "Kesha_Williams@investor.biz",
                    "first_name": "Kesha",
                    "last_name": "Williams",
                    "type": "personal"
                },
                {
                    "id": "66707bb0bd445fdc47fb84cf557dfd15",
                    "email": "Juanita_Ma@hongkongexchange.hk",
                    "first_name": "Juanita",
                    "last_name": "Ma",
                    "type": "personal"
                },
                {
                    "id": "6655dbbcc24cb56fb205e53bb015595c",
                    "email": "Antoine_LaVey@mailme.com",
                    "first_name": "Antoine",
                    "last_name": "LaVey",
                    "type": "personal"
                }
            ]
        }
    ]
}
----
====

*Results*:

* Three _contacts_ are created.
* The _contacts_ are placed in the _contact list_.
