=== Change the parameters of a search

____

This scenario demonstrates how to modify the parameters of an existing _search_.

*Prerequisites*: to follow this scenario, ensure that at least one _permanent_ search exists in InfoNgen.
This scenario is based on the result of the <<#create-a-search,Create a search>> scenario.

*Expected results*:

* The _search_ includes information about the dividends of two companies, *ExxonMobil* and *Saudi Aramco* (for example purposes, but any company is OK).
* The _search_ is visible to other _users_ besides its creator.
Unique _user_ IDs are `8b5477581d6753b10ac8f179fec1da01` and `550e8400e29b41d4a716446655440002`.
* The name of the _search_ reflects these changes.

*Related topics*: <<general/overview.adoc#reference-api,Reference API>>, <<general/overview.adoc#search-api,Search API>>, <<devdata/search.adoc#introduction-to-a-search,Introduction to a _search_>>.
____

[float]
==== 1. Find the tag that corresponds to "Saudi Aramco"

Run a `GET reference/tags/{{tagname}}` request with the `text=saudi%20arabian%20oil` query parameter. +
See the request described in the <<#1-find-the-unique-id-of-a-company,Find the unique ID of a company>> part of the <<#create-a-search,Create a search>> scenario.

.Click here for Reference API response with one company found (one value of the `company` _tag_).
[%collapsible]
====
----
HTTP/1.1 200 OK
X-Total: 1
----
[source,json]
----
[
    {
        "display": "Company",
        "name": "company",
        "primary": false,
        "values": [
            {
                "value": "100597510",
                "display": "Saudi Arabian Oil Co",
                "root": true,
                "has_children": false
            }
        ]
    }
]
----
====

InfoNgen returns the `"value": "100597510"` of the `company` _tag_, which is the InfoNgen ID of the Saudi Aramco Oil Company.

[float]
==== 2. Retrieve the search payload for modification

To modify the existing _search_ (the unique ID is `"7b6d78ca-a40f-4b24-9528-24200398c7b9"`), you may need to return its payload first.
It is possible to just enter a new payload in step 3 to overwrite the existing one.
The payload of a `POST searches` method changes after being processed by InfoNgen.
To view the payload of the created _search_, run the `GET searches/{{search_uid}}` request.
----
curl --location --request GET '{{API_link}}searches/7b6d78ca-a40f-4b24-9528-24200398c7b9' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for Search API response with the parameters of the _search_.
[%collapsible]
====
----
HTTP/1.1 200 OK
----

[source,json]
----
{
    "uid": "7b6d78ca-a40f-4b24-9528-24200398c7b9",
    "name": "exxon",
    "visibility": {
        "scope": "owner"
    },
    "created_at": "2019-09-20T14:15:21.943Z",
    "updated_at": "2019-09-25T14:54:12.88Z",
    "payload": {
        "conditions": [
            {
                "name": "company",
                "operator": "OR",
                "values": [
                    "100003436"
                ]
            },
            {
                "nested_conditions": [
                    {
                        "name": "relation",
                        "nested_conditions": [
                            {
                                "name": "relation.predicates.polarity",
                                "operator": "AND",
                                "values": [
                                    "positive"
                                ]
                            },
                            {
                                "name": "relation.subject.company",
                                "operator": "AND",
                                "values": [
                                    "100003436"
                                ]
                            },
                            {
                                "name": "relation.object.aspect",
                                "operator": "AND",
                                "values": [
                                    "Dividends"
                                ]
                            }
                        ],
                        "operator": "AND"
                    }
                ],
                "operator": "OR"
            }
        ],
        "search_settings": {
            "clustering": "Uri",
            "date_range": "Last90Days",
            "limit": 10,
            "page": 1,
            "relevancy": "Low"
        }
    },
    "creator": "{{your_unique_user_id}}"
}
----
====

The response contains the `"payload"` object that is necessary for the next step.

Note how the original search criteria were transformed:

* The `"sentiment_conditions"` array became a part of `"nested_conditions"` array.
** The `"aspect": "dividends"` object became `{"name": "relation.object.aspect","operator": "AND","values": ["Dividends"]}`.
** The `"polarity": "positive"` object became `{"name": "relation.predicates.polarity","operator": "AND","values": ["positive"]}`.
** The value of the `company` _tag_ is now found in the `{"name": "relation.subject.company", "operator": "AND","values": ["100003436"]}` object.

[float]
==== 3. Modify the payload of the search

To retrieve the _documents_ with positive _sentiments_ about *Saudi Aramco*'s dividends together with the _documents_ about the dividends of *Exxon Mobil*, we need to add another nested condition to the payload. +
The condition includes the `company` _tag_ value for *Saudi Aramco*—`"100597510"`. +
Both nested conditions are linked by a logical operand `OR` to retrieve documents either about *ExxonMobil* or *Saudi Aramco* (but not both).

To view the results of the updated _search_ immediately, add the `redirect_to_results=true` query parameter. By default it is set to `false`.

----
curl --location --request PUT '{{API_link}}/searches/7b6d78ca-a40f-4b24-9528-24200398c7b9/name' \
--header 'Content-Type: text/plain' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw
----
[source,json]
----
'{
    "conditions": [
        {
            "nested_conditions": [
                {
                    "name": "relation",
                    "nested_conditions": [
                        {
                            "name": "relation.predicates.polarity",
                            "operator": "AND",
                            "values": [
                                "positive"
                            ]
                        },
                        {
                            "name": "relation.subject.company",
                            "operator": "AND",
                            "values": [
                                "100003436"
                            ]
                        },
                        {
                            "name": "relation.object.aspect",
                            "operator": "AND",
                            "values": [
                                "Dividends"
                            ]
                        }
                    ],
                    "operator": "AND"
                },
                {
                    "name": "relation",
                    "nested_conditions": [
                        {
                            "name": "relation.predicates.polarity",
                            "operator": "AND",
                            "values": [
                                "positive"
                            ]
                        },
                        {
                            "name": "relation.subject.company",
                            "operator": "AND",
                            "values": [
                                "100597510"
                            ]
                        },
                        {
                            "name": "relation.object.aspect",
                            "operator": "AND",
                            "values": [
                                "Dividends"
                            ]
                        }
                    ],
                    "operator": "AND"
                }
            ],
            "operator": "OR"
        }
    ],
    "search_settings": {
        "clustering": "Uri",
        "date_range": "Last90Days",
        "limit": 10,
        "page": 1,
        "relevancy": "Low"
    }
}'
----
.Click here for Search API response with the _documents_ that correspond to the modified _search_ criteria.
[%collapsible]
====
The response is truncated for brevity.

----
HTTP/1.1 303 See Other
Location: {{API_link}}/searches/7b6d78ca-a40f-4b24-9528-24200398c7b9/results?show_options=search_info,documents&limit=10&page=1

HTTP/1.1 200 OK
Content-Type: application/json
----

[source,json]
----
{
    "documents": [
        {...},
        {...}
        {   "category": "Business & Financial Publications",
            "contributor": "Forbes",
            "headline": "5 Questions About The Aramco IPO That Really Matter To Investors",
            "id": "8411717639",
            "image_uri": "https://specials-images.forbesimg.com/imageserve/42962293/0x600.jpg?fit=scale",
            "published_at": "2019-09-03T19:51:24.12Z",
            "sentiments": [
                {
                    "subject": {
                        "display_name": "PrimaryCompany",
                        "name": "company",
                        "values": [
                            {
                                "display_value": "Saudi Arabian Oil Co",
                                "value": "100597510"
                            }
                        ]
                    },
                    "polarities": [
                        {
                            "aspects": [
                                {
                                    "text": [
                                        "High dividend rates will increase the value of the shares, but low dividend rates would likely scare away<br>
                                        investors when they see that the government collects tens of billions of dollars in dividend from the company each quarter."
                                    ],
                                    "name": "Dividends"
                                }
                            ],
                            "polarity": "positive",
                            "text": [
                                "High dividend rates will increase the value of the shares, but low dividend rates would likely scare away<br>
                                investors when they see that the government collects tens of billions of dollars in dividend from the company each quarter."
                            ]
                        }
                    ],
                    "text": [
                        "High dividend rates will increase the value of the shares, but low dividend rates would likely scare away investors<br>
                        when they see that the government collects tens of billions of dollars in dividend from the company each quarter."
                    ]
                }
            ],
            "source": "Forbes | Investing",
            "summary": "The 5 things the world really needs to know about the Aramco IPO.",
            "tags": [...],
            "uri": "https://{{Discovery_Portal_base_address}}.infongen.com/searches/documents/1411717631",
            "sharing_allowed": true
        },
        {...},
        {...}
    ],
    "documents_total": 81,
    "search_info": {
        "uid": "7b6d78ca-a40f-4b24-9528-24200398c7b9",
        "name": "exxon",
        "visibility": {
            "scope": "owner"
        },
        "created_at": "2019-09-20T14:15:21.943Z",
        "updated_at": "2019-09-26T11:14:56.54Z",
        "creator": "{{your_unique_user_id}}"
    }
}
----
====

The _search_ now returns _documents_ with positive _sentiments_ about *Saudi Aramco*'s dividends together with the _documents_ about *ExxonMobil*'s dividends.

[float]
==== 4. Rename the search

The name of the _search_ is still "exxon" `"search_info": {"name": "exxon"}`.
As the payload changes, you can make the name reflect this change. +
To change the name of the _search_, run the `PUT searches/{{search_uid}}/name` request. +
Enter the new name of the _search_ as plain text in the request body.

----
curl --location --request PUT '{{API_link}}/7b6d78ca-a40f-4b24-9528-24200398c7b9/name' \
--header 'Content-Type: text/plain' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw '"Exxon"'
----
The response returns the `204 No Content` status code, which means that the request was successful.
----
HTTP/1.1 204 No Content
Content-Type: application/json
----

[float]
==== 5. Allow other users access to the search you created

By default, each new _search_ that is created in InfoNgen is visible only to its creator.  +
To allow other _users_ access to the _search_, run a `PUT searches/{{search_uid}}/visibility` request.

The `"scope": "users"` parameter includes the array of unique _user_ IDs of people that can access the _search_.

----
curl --location --request PUT '{{API_link}}/searches/7b6d78ca-a40f-4b24-9528-24200398c7b9/visibility' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw
----
[source,json]
----
'{
    "scope": "users",
    "users": [
        "8b5477581d6753b10ac8f179fec1da01",
        "550e8400e29b41d4a716446655440002"
    ]
}'
----
To view the properties of the modified _search_, run the `GET searches/{{search_uid}}` request.
----
curl --location --request GET '{{API_link}}searches/7b6d78ca-a40f-4b24-9528-24200398c7b9' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for Search API response with the modified parameters of the `search`.
[%collapsible]
====
----
HTTP/1.1 200 OK
----

[source,json]
----
{
    "uid": "7b6d78ca-a40f-4b24-9528-24200398c7b9",
    "name": "Exxon and Saudi Aramco",
    "visibility": {
      "scope": "users",
      "users": [
          "8b5477581d6753b10ac8f179fec1da01",
          "550e8400e29b41d4a716446655440002"
      ]
    },
    "created_at": "2019-09-20T14:15:21.943Z",
    "updated_at": "2019-09-26T13:26:18.675Z",
    "payload": {
        "conditions": [
            {
                "nested_conditions": [
                    {
                        "name": "relation",
                        "nested_conditions": [
                            {
                                "name": "relation.predicates.polarity",
                                "operator": "AND",
                                "values": [
                                    "positive"
                                ]
                            },
                            {
                                "name": "relation.subject.company",
                                "operator": "AND",
                                "values": [
                                    "100003436"
                                ]
                            },
                            {
                                "name": "relation.object.aspect",
                                "operator": "AND",
                                "values": [
                                    "Dividends"
                                ]
                            }
                        ],
                        "operator": "AND"
                    },
                    {
                        "name": "relation",
                        "nested_conditions": [
                            {
                                "name": "relation.predicates.polarity",
                                "operator": "AND",
                                "values": [
                                    "positive"
                                ]
                            },
                            {
                                "name": "relation.subject.company",
                                "operator": "AND",
                                "values": [
                                    "100597510"
                                ]
                            },
                            {
                                "name": "relation.object.aspect",
                                "operator": "AND",
                                "values": [
                                    "Dividends"
                                ]
                            }
                        ],
                        "operator": "AND"
                    }
                ],
                "operator": "OR"
            }
        ],
        "search_settings": {
            "clustering": "Uri",
            "date_range": "Last90Days",
            "limit": 10,
            "page": 1,
            "relevancy": "Low"
        }
    },
    "creator": "{{your_unique_user_id}}"
}
----
====

*Results*:

* The payload of the _search_ changed.
* The name of the _search_ is `Exxon and Saudi Aramco`.
* Two _users_ have access to the _search_ besides the creator.
