=== Subscribe to a search
____
This scenario describes how to use the functionality of Subscriptions API to create an automatic e-mail with updates from the results of a _permanent search_.

*Prerequisites*

To follow this scenario, ensure that you have:

* One _permanent search_ (see the <<#create-a-search,Create a _search_>> scenario).
* One _contact list_ (see the <<#create-a-contact-list,Create a _contact list_>> scenario).

*Expected results*:

* Subscription to the "Competitors" _permanent search_ is created.
* Subscription becomes active every weekday at 10:00 and repeats every two hours.
* Subscription is available to you (the current _user_) and your list of _contacts_.

*Related topics*: <<general/overview.adoc#address-book-api,Address Book API>>, <<general/overview.adoc#subscriptions-api,Subscriptions API>>, <<general/overview.adoc#search-api,Search API>>, <<general/overview.adoc#user-profile-api,User Profile API>>.
____

[float]
==== 1. Find the unique ID of the search

First, find the unique ID of the required _search_.
To view the list of _searches_, run the following API request:

----
curl --location --request GET '{{API_link}}/searches' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for Search API response with the list of all available _searches_
[%collapsible]
====
_Searches_ in the response are sorted lexicographically.
----
HTTP/1.1 200 OK
Content-Type: application/json
----
[source,json]
----
[
    {
        "uid": "ba2d851b-0306-4136-9ec4-cca74b2z5004",
        "name": "Competitors",
        "visibility": {
            "scope": "company"
            },
        "created_at": "2018-08-28T12:23:23.623Z",
        "updated_at": "2019-04-21T11:31:15.273Z",
        "creator": "{{some_user_uid}}"
    },
    {
        "uid": "7b6d78ca-a40f-4b24-9528-24200398c7b9",
        "name": "Exxon and Saudi Aramco",
        "visibility": {
          "visibility": {
            "scope": "users",
            "users": [
                "8b5477581d6753b10ac8f179fec1da01",
                "550e8400e29b41d4a716446655440002"
                ]
        },
        "created_at": "2019-09-20T14:15:21.943Z",
        "updated_at": "2019-09-26T13:26:18.675Z",
        "creator": "{{your_unique_user_id}}"
    },
    {
        "uid": "f88c8dh4-a54b-44dc-a9ac-bb518eaz1003",
        "name": "Investments",
        "visibility": {
            "scope": "owner"
        },
        "created_at": "2014-01-28T12:32:45.398Z",
        "updated_at": "2019-07-29T11:59:41.082Z",
        "creator": "{{your_unique_user_id}}"
    },
    {...}
]
----
====

The unique ID of the "Competitors" _search_ is `ba2d851b-0306-4136-9ec4-cca74b2z5004`.

[float]
==== 2. Find your own unique user ID and the ID of the contact list

There are three ways to find your unique user ID:

. As the creator of _searches_ in step 1, you can view your unique _user_ ID as the value of the `"creator"` parameter in the response.
. Another way to view the data that describe you is through the <<general/overview.adoc#user-profile-api,User Profile API>>. +
To view your _user_ profile that is stored in InfoNgen, run the `GET user/profile` request.

----
curl --location --request GET '{{API_link}}/user/profile' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for User API response with your _user_ data.
[%collapsible]
====
----
HTTP/1.1 200 OK
Content-Type: application/json
----

[source,json]
----
{
    "code": "b34567890123456f8f1e12d891474d2e",
    "client_code": "42",
    "client_name": "InfoNgen",
    "company_code": "500",
    "company_name": "Fortune500company",
    "email": "John_Wick@Fortune500company.com",
    "first_name": "John",
    "last_name": "Wick",
    "time_zone": "UTC",
    "status": "Active",
    "roles": [
        "API_User",
        "Admin"
    ]
}
----
====

The unique ID of the current _user_—your unique ID—is the value of the `"code"` parameter: `"b34567890123456f8f1e12d891474d2e"`.

. The third option is to use the functionality of <<general/overview.adoc#address-book-api,Address Book API>>.
You can see your unique _user_ ID, as well as the unique ID of the necessary _contact list_.

----
curl --location --request GET '{API_link}}/addressbook' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
See the response in <<#2-create-a-contact-list-with-the-new-contacts,Create a _contact list_ with the new _contacts_>> section of the <<#create-a-contact-list,Create a _contact list_>> scenario.

* Your unique ID is the value of the `"id"` parameter in the `"contacts"` array: `"b34567890123456f8f1e12d891474d2e"`.
* The unique ID of the _contact list_ is the value of the `"id"` parameter in the `"contact_lists"` array: `3362`.

[float]
==== 3. Create a subscription

The _subscription_ for a _search_ must have the same unique ID as the _search_.
See the <<general/overview.adoc#subscription-api,Subscription API>> for a more detailed description of the _subscription_ object.

Create a _subscription_ that occurs every two hours from Monday to Friday, starting from 10:00 and onwards:

* Populate the `"days"` array with weekdays.
* Set the required time interval for the _subscription_ in `"effective_from"` and `"effective_till"`.
* Use the `"recurrence"` parameter to show how often a subscription must send you the _documents_ found by your _search_ (in seconds).
* Put your unique ID in the `"users"` array.

----
curl --location --request POST '{{API_link}}/subscriptions/search:ba2d851b-0306-4136-9ec4-cca74b2z5004/schedules' \
--header 'Content-Type: application/json' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data-raw '
----
[source,json]
----
'[
    {
        "payload": {
            "days": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday"
            ],
            "effective_from": "10:00:00",
            "effective_till": "17:00:00",
            "recurrence": 7200,
            "zerotime": "2019-09-27T09:00:00Z"
        },
        "recipients": {
            "users": [
                "b34567890123456f8f1e12d891474d2e"
            ],
            "contact_lists": [
                3362
            ]
        }
    }
]'
----

The response returns the `202 Accepted` status code, which means that the request was successful.

----
HTTP/1.1 202 Accepted
Content-Type: application/json
----

Run the `GET subscription/{{subscription_uid}}` request to check if the _subscription_ is set correctly:

----
curl --location --request GET '{{API_link}}/subscriptions/search:ba2d851b-0306-4136-9ec4-cca74b2z5004' \
--header 'x-api-key: {{x-api-key}}' \
--header 'Authorization: Bearer {{access_token}}'
----
.Click here for Subscription API response with new _subscription_ data.
[%collapsible]
====
----
HTTP/1.1 200 OK
Content-Type: application/json
----

[source,json]
----
[
    {
        "enabled": true,
        "kind": "search",
        "schedules": [
            {
                "uid": "166316",
                "payload": {
                    "days": [
                        "Monday",
                        "Tuesday",
                        "Wednesday",
                        "Thursday",
                        "Friday"
                    ],
                    "effective_from": "10:00:00",
                    "effective_till": "17:00:00",
                    "recurrence": 7200,
                    "zerotime": "2019-09-27T09:00:00"
                },
                "time_zones": [
                    "Arab Standard Time",
                    "Eastern Standard Time"
                ],
                "recipients": {
                    "users": [
                        "b34567890123456f8f1e12d891474d2e",
                        "6655dbbcc24cb56fb205e53bb015595c",
                        "6664d12f6823297a859f25cf87534fa1",
                        "66707bb0bd445fdc47fb84cf557dfd15"
                    ],
                    "contact_lists": [
                        3362
                    ],
                    "total_count": 4
                },
                "properties": {
                    "Creator": "b34567890123456f8f1e12d891474d2e"
                }
            }
        ],
        "uid": "search:ba2d851b-0306-4136-9ec4-cca74b2z5004"
    }
]
----
====

*Results*:

* The _subscription_ occurs every two hours on weekdays, starting from 10:00.
* You are the recipient together with your _contacts_.
